name: Replit Auto Sync

on:
  push:
    branches:
      - main

jobs:
  echo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Güncelleme Bildirisi
        run: echo "✅ Replit üzerinden bir güncelleme yapıldı!"
